#!/bin/sh

curl -X POST -H "Content-Type: application/json" -H "x-api-key:{API_KEY}" -d "{\"value\":\"${1}\"}" -s https://{API_ID}.execute-api.ap-northeast-1.amazonaws.com/{STAGE_NAME}/ | jq .popcount
